name: Build and Push with Kaniko

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted 

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Docker Auth Config
        run: |
          mkdir -p ~/.docker
          echo '{"auths": {"ghcr.io":{"auth":"'$(echo -n "${{ github.actor }}:${{ secrets.GHCR_TOKEN }}" | base64)'"}}}' > ~/.docker/config.json

      - name: Generate Short SHA Tag
        id: vars
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          TIMESTAMP=$(date +'%Y%m%d-%H%M%S')
          echo "tag=main-${TIMESTAMP}-${SHORT_SHA}" >> $GITHUB_OUTPUT

      - name: Build and Push Image via Kaniko
        run: |
          docker run --rm \
            -v ${{ github.workspace }}:/workspace \
            -v ~/.docker/config.json:/kaniko/.docker/config.json:ro \
            gcr.io/kaniko-project/executor:latest \
            --context=/workspace \
            --dockerfile=/workspace/Dockerfile \
            --destination=ghcr.io/${{ github.repository }}:latest \
            --destination=ghcr.io/${{ github.repository }}:${{ steps.vars.outputs.tag }} \
            --cache=true